import { tournamentFormat } from '../config/tournamentFormat.js'

export const languageOptions = [
  { id: 'en', label: 'English', shortLabel: 'EN', direction: 'ltr' },
  { id: 'he', label: 'עברית', shortLabel: 'HE', direction: 'rtl' },
  { id: 'ar', label: 'العربية', shortLabel: 'AR', direction: 'rtl' },
]

const languageStorageKey = 'deir-hanna-world-cup-language'
const fallbackLanguage = 'en'
const defaultLanguage = 'ar'
const uiTranslations = {
  en: {
    addAssist: 'Add Assist',
    addGoal: 'Add Goal',
    addMatch: 'Add match',
    addOwnGoal: 'Add Own Goal',
    addPlayer: 'Add player',
    addRedCard: 'Add Red Card',
    addTeam: 'Add team',
    addYellowCard: 'Add Yellow Card',
    admin: 'Admin',
    adminAccess: 'Admin Access',
    adminAccessConfirmed: 'Admin access confirmed.',
    adminControlPanel: 'Control panel',
    adminEmail: 'Admin email',
    adminInviteError: 'Could not invite admin.',
    adminInviteSuccess: '{{email}} can now log in as admin.',
    adminLiveControl: 'Admin live control',
    adminSettings: 'Admin Settings',
    allTeams: 'All teams',
    appearance: 'Appearance',
    assist: 'Assist',
    assists: 'Assists',
    back: 'Back',
    backToOverview: 'Back to Overview',
    bestPlayer: 'Best player',
    beFirstToVote: 'Be first to vote',
    bench: 'Bench',
    byDate: 'By date',
    byRound: 'By round',
    byTeam: 'By team',
    cancel: 'Cancel',
    chartDataUnavailable: 'No chart data yet.',
    closeBracket: 'Close bracket',
    closeEventForm: 'Close event form',
    closeQuickMode: 'Close Quick Mode',
    code: 'Code',
    completed: 'Completed',
    competition: 'Competition',
    compareTeams: 'Compare Teams',
    connectingToSupabase: 'Connecting to Supabase.',
    contributions: 'Contributions',
    currentData: 'Current data',
    date: 'Date',
    deleteMatch: 'Delete match',
    developedBy: 'Developed by Mohammad Ragab',
    details: 'Details',
    darkMode: 'Dark mode',
    dismiss: 'Dismiss',
    draw: 'Draw',
    drawAvailableForLeague: 'Draw is available for group-stage games',
    disciplinaryEvent: 'Disciplinary event',
    edit: 'Edit',
    editMatch: 'Edit Match',
    endFirstHalfHalftime: 'End First Half / Halftime',
    endMatch: 'End Match',
    eventTimeline: 'Event Timeline',
    eventType: 'Event type',
    eventSaveFailed: 'Event could not be saved. Please try again.',
    expand: 'Expand',
    favoriteTeam: 'Favorite team',
    fieldSharing: 'Field sharing',
    fixtures: 'fixtures',
    final: 'Final',
    finalScoreSaved: 'Final score saved. Live actions are closed for this match.',
    finishedMatchEditing: 'You can still correct the score and event timeline after full time.',
    finished: 'Finished',
    firstHalf: 'First half',
    fullTime: 'Full time',
    goal: 'Goal',
    goals: 'Goals',
    goalDifferenceShort: 'GD',
    group: 'Group',
    groupA: 'Group A',
    groupB: 'Group B',
    groupStage: 'Group stage',
    halftime: 'Halftime',
    kickoff: 'Kickoff',
    knockout: 'Knockout',
    knockoutMatch: 'Knockout match',
    knockoutPath: 'Knockout Path',
    language: 'Language',
    latestMatchday: 'Latest Matchday',
    league: 'Group stage',
    leagueStage: 'Group stage',
    leagueStandings: 'Group Standings',
    leagueTable: 'Group Tables',
    lineups: 'Lineups',
    lightMode: 'Light mode',
    live: 'Live',
    liveMatch: 'Live match',
    liveMatchControl: 'Live Match Control',
    liveMatches: 'Live matches',
    liveNow: 'LIVE NOW',
    liveTableProvisional: 'Live table — provisional',
    loadingTournamentData: 'Loading tournament data',
    localTournamentDashboard: 'Local tournament dashboard',
    login: 'Login',
    loginAsAdmin: 'Login as admin',
    match: 'Match',
    matchCenter: 'Match Center',
    matchEvents: 'Match Events',
    matchHistory: 'Match History',
    matchSetup: 'Match Setup',
    matchday: 'Matchday',
    matches: 'Matches',
    minute: 'Minute',
    max: 'Max',
    mostAssists: 'Most Assists',
    nextMatch: 'Next Match',
    nextMatchday: 'Next Matchday',
    latestResults: 'Latest results',
    lastMatches: 'Last matches',
    noAssist: 'No assist',
    noAssistPlayersFound: 'No assist players found.',
    noGoalsOrAssistsYet: 'No goals or assists recorded yet.',
    noGoalsRecordedYet: 'No goals recorded yet.',
    noMatchEventsForMatchYet: 'No match events recorded for this match yet.',
    noMatchEventsYet: 'No match events recorded yet.',
    noMatchHistoryYet: 'No match history yet.',
    noMatchScheduledYet: 'No match scheduled yet.',
    noMatchesAvailableForStageYet: 'No matches available for this stage yet.',
    noMatchesFoundForFilter: 'No matches found for this filter.',
    noMatchesScheduledYet: 'No matches scheduled yet.',
    noMatchesToday: 'No matches today.',
    noPlayersFound: 'No players found.',
    noPlayersAvailable: 'No players available',
    noPlayersYet: 'No players yet.',
    noPlayersRegistered: 'No players registered',
    noRecordYet: 'No record yet',
    noRelatedMatchesYet: 'No related matches yet.',
    overview: 'Overview',
    ownGoal: 'Own Goal',
    ownGoalDetail: 'Goal awarded to the opponent.',
    ownGoalScorer: 'Own goal scorer',
    ownGoalTeamHelp: "Select the player's team. The score is awarded to the opposing team automatically.",
    pageNotFound: 'Page not found',
    pageNotFoundDetail: 'This tournament page could not be found. It may have been removed or the link may be old.',
    pause: 'Pause',
    paused: 'Paused',
    penalty: 'Penalty',
    penaltyGoal: 'Penalty goal',
    penaltyGoalDetail: 'Penalty scored.',
    penaltyMissSaved: 'Miss/Saved',
    penaltyMissSavedDetail: 'Penalty missed or saved.',
    penaltyResult: 'Penalty result',
    penaltyShooter: 'Penalty shooter',
    passAccuracy: 'Pass accuracy',
    player: 'Player',
    playerAlreadySentOff: 'Player has already been sent off.',
    playerProfile: 'Player profile',
    players: 'Players',
    playersCount: 'players',
    playedShort: 'P',
    points: 'Points',
    pointsShort: 'PTS',
    popUpBlockedPrint: 'Pop-up blocked. Allow pop-ups to print the poster.',
    preparing: 'Preparing...',
    previousMatches: 'Previous matches',
    qualificationRace: 'Qualification Race',
    qualificationRules: 'Qualification Rules',
    quickLinks: 'Quick links',
    quickMode: 'Quick Mode',
    qrPoster: 'QR/Poster',
    rank: 'Rank',
    ranking: 'Ranking',
    relatedMatches: 'Related Matches',
    recentEventsUpdateImmediately: 'Recent events update immediately after saving.',
    recentFixtures: 'Recent fixtures',
    recentForm: 'Recent Form',
    redCard: 'Red card',
    redCards: 'Red cards',
    readyForRealData: 'Ready for real tournament data',
    record: 'Record',
    realDataEmptyState: 'Demo teams, players, fixtures, and fake stats are no longer used. Sign in as admin to add the real teams, squads, fixtures, and match timeline manually.',
    resume: 'Resume',
    round: 'Round',
    roundShort: 'Round {{round}}',
    rules: 'Rules',
    save: 'Save',
    saveDetails: 'Save details',
    schedule: 'Schedule',
    scheduled: 'Scheduled',
    scanToFollow: 'Scan to follow live matches, standings, scorers and results',
    searchAssistPlayer: 'Search assist player',
    searchPlayer: 'Search player',
    searchPlayers: 'Search players',
    selectPlayer: 'Select player',
    scorer: 'Scorer',
    score: 'Score',
    secondHalf: 'Second half',
    secondYellowDismissal: 'Automatic dismissal after second yellow card.',
    secondYellowRedCard: 'Second Yellow → Red Card',
    selectRound: 'Select round',
    selectTeam: 'Select team',
    semiFinal: 'Semi-final',
    semiFinals: 'Semi-finals',
    sendLoginLink: 'Send login link',
    scheduleRematch: 'Schedule rematch',
    shareTeam: 'Share team',
    share: 'Share',
    shareImage: 'Share Image',
    shareSheetOpened: 'Share sheet opened.',
    sharing: 'Sharing',
    sharingNotSupportedDownloaded: 'Sharing is not supported on this browser. Image downloaded instead.',
    shots: 'Shots',
    singleGameBracket: 'Single-game bracket',
    square: 'Square',
    signOut: 'Sign out',
    signedInAs: 'Signed in as',
    startsIn: 'Starts in',
    startMatch: 'Start Match',
    startSecondHalf: 'Start Second Half',
    standings: 'Standings',
    standingsAvailableForLeague: 'Standings are available for group-stage matches.',
    standingsPreview: 'Standings Preview',
    standaloneAssistEvent: 'Standalone assist event',
    starters: 'Starters',
    stats: 'Stats',
    status: 'Status',
    statistics: 'Statistics',
    story: 'Story',
    suspended: 'Suspended',
    suspendedPlayers: 'Suspended players',
    suspensionStatus: 'Suspension status',
    table: 'Table',
    team: 'Team',
    teams: 'Teams',
    teamsAndPlayers: 'Teams & Players',
    team1: 'Team 1',
    team2: 'Team 2',
    tbd: 'TBD',
    theme: 'Theme',
    teamPage: 'Team Page',
    teamPlayers: '{{team}} players',
    thirdPlace: 'Third place',
    thisEmailIsNotAdmin: 'This email is signed in but is not listed in admin_users.',
    time: 'Time',
    today: 'Today',
    todayMatches: "Today's Matches",
    topAdvance: 'Top {{count}} advance',
    topQualify: 'Top {{count}} qualify',
    topTwoEachGroup: 'Top 2 from each group qualify',
    topScorer: 'Top scorer',
    tournament: 'Tournament',
    tournamentTitle: 'Deir Hanna World Cup',
    tournamentForm: 'Tournament form',
    tournamentStats: 'Tournament Stats',
    tournamentWinner: 'Tournament winner',
    tournamentTotals: 'Tournament totals',
    venue: 'Venue',
    unavailable: 'Unavailable',
    unassisted: 'Unassisted',
    undoLastEvent: 'Undo last event',
    editLastEvent: 'Edit last event',
    editEvent: 'Edit event',
    deleteEvent: 'Delete event',
    deleteEventConfirm: 'Delete this event and recalculate the score/stats?',
    eventDeletedSuccessfully: 'Event deleted successfully.',
    correctLiveMinute: 'Correct live minute',
    applyMinuteCorrection: 'Apply minute',
    minuteCorrectionHelp: 'Use this if kickoff or the second half started late. The live clock will continue from the corrected minute.',
    confirmEvent: 'Confirm {{event}}',
    endMatchConfirm: 'End this match and keep the current score as final?',
    goalsAndAssists: 'Goals and assists',
    goalsAssistsByMatch: 'Goals / Assists by Match',
    goalsByMatch: 'Goals by Match',
    goalsScored: 'Goals scored',
    goalsConceded: 'Goals conceded',
    mostScored: 'Most scored',
    fewestConceded: 'Fewest conceded',
    wins: 'Wins',
    draws: 'Draws',
    losses: 'Losses',
    wonShort: 'W',
    drawnShort: 'D',
    lostShort: 'L',
    shortTable: 'Short table',
    fullTable: 'Full table',
    form: 'Form',
    minutes: 'Minutes',
    pendingStats: 'Pending stats',
    pGdPts: 'P / GD / PTS',
    bracketViewer: 'Bracket viewer',
    bothTeams: 'Both teams',
    matchShareCard: 'Match Share Card',
    shareCardDestinations: 'Instagram, WhatsApp, Facebook, Telegram',
    matchShareCardPreview: 'Match share card preview',
    imageDownloaded: 'Image downloaded.',
    inviteAdmin: 'Invite Admin',
    inviteAdminDetail: 'Add another approved admin email',
    downloadImage: 'Download Image',
    shareImageButton: 'Share Image',
    generating: 'Generating...',
    couldNotGenerateImage: 'Could not generate image.',
    posterDownloaded: 'Poster downloaded.',
    printDialogOpened: 'Print dialog opened.',
    couldNotGeneratePoster: 'Could not generate poster.',
    couldNotGenerateQrCode: 'Could not generate QR code.',
    generatingQrPoster: 'Generating QR poster...',
    downloadPoster: 'Download poster',
    printPoster: 'Print poster',
    qrPosterPreview: 'QR poster preview',
    openCameraAndScan: 'Open the camera and scan',
    noLoginRequiredForSpectators: 'No login required for spectators',
    matchCardShareText: 'Deir Hanna World Cup match card',
    liveMatchesAria: 'Show live matches',
    openLiveMatch: 'Open live match',
    favoriteMatch: 'Favorite match',
    favoriteTeamLabel: 'Favorite team',
    minutesAutoCalculated: 'Minutes are calculated automatically during live matches.',
    addEvent: 'Add Event',
    adminUpdates: 'Admin updates',
    adminUpdatesDetail: 'Secure score and event entry',
    cancelEvent: 'Cancel event',
    deleteMatchConfirm: 'Delete this match and its events?',
    deletePlayer: 'Delete player',
    deletePlayerConfirm: 'Delete {{name}}?',
    deleteTeam: 'Delete team',
    deleteTeamConfirm: 'Delete {{name}}? This also removes its players.',
    editOrDelete: 'Edit or delete',
    finalResult: 'Final Result',
    fixture: 'Fixture',
    fixtureSetup: 'Fixture setup',
    followLive: 'Follow live',
    goalscorers: 'Goalscorers',
    lineupsUnavailable: 'Lineups will appear when both teams are confirmed.',
    managePlayers: 'Manage Players',
    manageTeams: 'Manage Teams',
    mvpFirst: 'MVP first',
    noPlayersAdmin: 'No players yet. Add real squads after creating teams.',
    noTeamsYet: 'No teams yet. Add the real tournament teams first.',
    playerName: 'Player name',
    playerNameArabic: 'Player name - Arabic',
    playerNameEnglish: 'Player name - English',
    playerNameHebrew: 'Player name - Hebrew',
    primary: 'Primary',
    publicDashboard: 'Public dashboard',
    publicDashboardDetail: 'Fixtures, live scores, tables, leaders',
    pwaRelease: 'PWA release',
    pwaReleaseDetail: 'Installable QR-code access',
    scoreAndDetails: 'Score and details',
    secondary: 'Secondary',
    squadFull: 'Squad full',
    squadManagement: 'Squad management',
    squadSlots: 'Squad slots',
    stage: 'Stage',
    startingSeven: 'Starting Seven',
    teamName: 'Team name',
    teamNameArabic: 'Team name - Arabic',
    teamNameEnglish: 'Team name - English',
    teamNameHebrew: 'Team name - Hebrew',
    tournamentSetup: 'Tournament setup',
    versionRoadmap: 'Version Roadmap',
    tiebreakersSummary: 'Tiebreakers: points, then head-to-head result.',
    semiFinalWinners: 'Semi-final winners',
    winnersAdvance: 'Winners advance',
    winnerAdvances: 'Winner advances',
    championDecided: 'Champion decided',
    thirdPlaceDecided: 'Third place decided',
    actionFailed: 'Action failed. Please try again.',
    adding: 'Adding...',
    saving: 'Saving...',
    deleting: 'Deleting...',
    teamAddedSuccessfully: 'Team added successfully.',
    playerAddedSuccessfully: 'Player added successfully.',
    matchAddedSuccessfully: 'Match added successfully.',
    changesSavedSuccessfully: 'Changes saved successfully.',
    deletedSuccessfully: 'Deleted successfully.',
    qualificationRequiresRematch: 'Qualification requires rematch.',
    rematchAdminSuggestion: 'Schedule a rematch manually from Add Match. Do not assign date/time until the organizer confirms it.',
    vote: 'Vote',
    votes: 'votes',
    whoWillWin: 'Who will win?',
    yellowCard: 'Yellow card',
    yellowCards: 'Yellow cards',
  },
  he: {
    addAssist: 'הוסף בישול',
    addGoal: 'הוסף שער',
    addMatch: 'הוסף משחק',
    addOwnGoal: 'הוסף שער עצמי',
    addPlayer: 'הוסף שחקן',
    addRedCard: 'הוסף כרטיס אדום',
    addTeam: 'הוסף קבוצה',
    addYellowCard: 'הוסף כרטיס צהוב',
    admin: 'ניהול',
    adminAccess: 'גישת מנהל',
    adminAccessConfirmed: 'גישת מנהל אושרה.',
    adminControlPanel: 'לוח בקרה',
    adminEmail: 'אימייל מנהל',
    adminInviteError: 'לא ניתן להזמין מנהל.',
    adminInviteSuccess: '{{email}} יכול/ה עכשיו להתחבר כמנהל.',
    adminSettings: 'הגדרות מנהל',
    allTeams: 'כל הקבוצות',
    appearance: 'תצוגה',
    assists: 'בישולים',
    assist: 'בישול',
    back: 'חזרה',
    backToOverview: 'חזרה לסקירה',
    bestPlayer: 'השחקן הטוב ביותר',
    beFirstToVote: 'היה הראשון להצביע',
    bench: 'ספסל',
    byDate: 'לפי תאריך',
    byRound: 'לפי סיבוב',
    byTeam: 'לפי קבוצה',
    cancel: 'ביטול',
    chartDataUnavailable: 'אין עדיין נתוני גרף.',
    code: 'קוד',
    completed: 'הושלם',
    competition: 'תחרות',
    compareTeams: 'השוואת קבוצות',
    connectingToSupabase: 'מתחבר ל-Supabase.',
    contributions: 'תרומות',
    currentData: 'נתונים נוכחיים',
    date: 'תאריך',
    deleteMatch: 'מחק משחק',
    developedBy: 'פותח על ידי מוחמד רגאב',
    details: 'פרטים',
    darkMode: 'מצב כהה',
    dismiss: 'סגור',
    draw: 'תיקו',
    drawAvailableForLeague: 'תיקו זמין במשחקי שלב הבתים',
    disciplinaryEvent: 'אירוע משמעתי',
    editMatch: 'ערוך משחק',
    endFirstHalfHalftime: 'סיים מחצית ראשונה / הפסקה',
    endMatch: 'סיים משחק',
    eventTimeline: 'ציר אירועים',
    eventType: 'סוג אירוע',
    eventSaveFailed: 'לא ניתן לשמור את האירוע. נסה שוב.',
    expand: 'הרחב',
    favoriteTeam: 'קבוצה מועדפת',
    fixtures: 'משחקים',
    final: 'גמר',
    finalScoreSaved: 'התוצאה הסופית נשמרה. פעולות המשחק נסגרו.',
    finishedMatchEditing: 'אפשר עדיין לתקן תוצאה ואירועים אחרי שריקת הסיום.',
    finished: 'הסתיים',
    firstHalf: 'מחצית ראשונה',
    fullTime: 'סיום',
    goal: 'שער',
    goals: 'שערים',
    goalDifferenceShort: 'הפרש',
    group: 'בית',
    groupA: 'בית א׳',
    groupB: 'בית ב׳',
    groupStage: 'שלב הבתים',
    halftime: 'מחצית',
    kickoff: 'שריקה',
    knockout: 'נוקאאוט',
    knockoutMatch: 'משחק נוקאאוט',
    knockoutPath: 'מסלול הנוקאאוט',
    language: 'שפה',
    latestMatchday: 'מחזור אחרון',
    latestResults: 'תוצאות אחרונות',
    league: 'שלב הבתים',
    leagueStage: 'שלב הבתים',
    leagueStandings: 'טבלאות הבתים',
    leagueTable: 'טבלאות הבתים',
    lineups: 'הרכבים',
    lightMode: 'מצב בהיר',
    live: 'חי',
    liveMatch: 'משחק חי',
    liveMatchControl: 'ניהול משחק חי',
    liveMatches: 'משחקים חיים',
    liveNow: 'חי עכשיו',
    liveTableProvisional: 'טבלה חיה — זמנית',
    loadingTournamentData: 'טוען נתוני טורניר',
    localTournamentDashboard: 'לוח טורניר מקומי',
    login: 'כניסה',
    loginAsAdmin: 'כניסת מנהל',
    match: 'משחק',
    matchCenter: 'מרכז המשחק',
    matchEvents: 'אירועי המשחק',
    matchHistory: 'היסטוריית משחקים',
    matchSetup: 'הגדרת משחקים',
    matchday: 'מחזור',
    matches: 'משחקים',
    minute: 'דקה',
    max: 'מקסימום',
    mostAssists: 'הכי הרבה בישולים',
    nextMatch: 'המשחק הבא',
    nextMatchday: 'המחזור הבא',
    noAssist: 'ללא בישול',
    noGoalsOrAssistsYet: 'אין עדיין שערים או בישולים.',
    noGoalsRecordedYet: 'אין עדיין שערים.',
    noMatchEventsForMatchYet: 'אין עדיין אירועים למשחק הזה.',
    noMatchEventsYet: 'אין עדיין אירועי משחק.',
    noMatchHistoryYet: 'אין עדיין היסטוריית משחקים.',
    noMatchScheduledYet: 'אין עדיין משחק מתוכנן.',
    noMatchesAvailableForStageYet: 'אין משחקים זמינים לשלב הזה.',
    noMatchesFoundForFilter: 'לא נמצאו משחקים למסנן הזה.',
    noMatchesScheduledYet: 'אין משחקים מתוכננים עדיין.',
    noMatchesToday: 'אין משחקים היום.',
    noPlayersFound: 'לא נמצאו שחקנים.',
    noPlayersYet: 'אין עדיין שחקנים.',
    noPlayersRegistered: 'אין שחקנים רשומים',
    noRecordYet: 'אין עדיין מאזן',
    overview: 'סקירה',
    ownGoal: 'שער עצמי',
    ownGoalDetail: 'השער נזקף לזכות היריבה.',
    ownGoalScorer: 'כובש שער עצמי',
    ownGoalTeamHelp: 'בחר את הקבוצה של השחקן. התוצאה תתווסף אוטומטית לקבוצה היריבה.',
    pageNotFound: 'העמוד לא נמצא',
    pageNotFoundDetail: 'עמוד הטורניר הזה לא נמצא. ייתכן שהוא הוסר או שהקישור ישן.',
    pause: 'השהה',
    paused: 'מושהה',
    penalty: 'פנדל',
    penaltyGoal: 'שער מפנדל',
    penaltyGoalDetail: 'פנדל נכבש.',
    penaltyMissSaved: 'החטאה/עצירה',
    penaltyMissSavedDetail: 'הפנדל הוחטא או נעצר.',
    penaltyResult: 'תוצאת הפנדל',
    penaltyShooter: 'בועט הפנדל',
    passAccuracy: 'דיוק מסירה',
    player: 'שחקן',
    playerAlreadySentOff: 'השחקן כבר הורחק.',
    playerProfile: 'פרופיל שחקן',
    players: 'שחקנים',
    playersCount: 'שחקנים',
    playedShort: 'מ',
    points: 'נקודות',
    pointsShort: 'נק׳',
    previousMatches: 'משחקים קודמים',
    qualificationRace: 'מאבק ההעפלה',
    qualificationRules: 'חוקי העפלה',
    quickLinks: 'קישורים מהירים',
    quickMode: 'מצב מהיר',
    qrPoster: 'קוד QR / פוסטר',
    rank: 'דירוג',
    ranking: 'מיקום',
    recentFixtures: 'משחקים אחרונים',
    recentForm: 'כושר אחרון',
    redCard: 'כרטיס אדום',
    redCards: 'כרטיסים אדומים',
    readyForRealData: 'מוכן לנתוני הטורניר האמיתיים',
    record: 'מאזן',
    realDataEmptyState: 'קבוצות דמו, שחקנים, משחקים וסטטיסטיקות מזויפות כבר לא בשימוש. התחבר כמנהל כדי להוסיף ידנית את הקבוצות, הסגלים, המשחקים וציר האירועים האמיתיים.',
    resume: 'המשך',
    round: 'סיבוב',
    roundShort: 'מחזור {{round}}',
    rules: 'חוקים',
    save: 'שמור',
    saveDetails: 'שמור פרטים',
    schedule: 'לוח משחקים',
    scheduled: 'מתוכנן',
    scanToFollow: 'סרקו כדי לעקוב אחרי משחקים חיים, טבלאות, כובשים ותוצאות',
    scorer: 'כובש',
    score: 'תוצאה',
    secondHalf: 'מחצית שנייה',
    secondYellowDismissal: 'הרחקה אוטומטית לאחר כרטיס צהוב שני.',
    secondYellowRedCard: 'צהוב שני → כרטיס אדום',
    selectRound: 'בחר סיבוב',
    selectTeam: 'בחר קבוצה',
    selectPlayer: 'בחר שחקן',
    semiFinal: 'חצי גמר',
    semiFinals: 'חצאי גמר',
    sendLoginLink: 'שלח קישור כניסה',
    scheduleRematch: 'קבע משחק חוזר',
    shareTeam: 'שתף קבוצה',
    shots: 'בעיטות',
    singleGameBracket: 'נוקאאוט במשחק אחד',
    signOut: 'התנתק',
    signedInAs: 'מחובר כ',
    startsIn: 'מתחיל בעוד',
    startMatch: 'התחל משחק',
    startSecondHalf: 'התחל מחצית שנייה',
    standings: 'טבלה',
    standingsAvailableForLeague: 'הטבלאות זמינות למשחקי שלב הבתים.',
    standingsPreview: 'תצוגת טבלה',
    standaloneAssistEvent: 'אירוע בישול נפרד',
    starters: 'פותחים',
    stats: 'סטטיסטיקות',
    status: 'סטטוס',
    statistics: 'סטטיסטיקה',
    suspended: 'מורחק',
    suspendedPlayers: 'שחקנים מושעים',
    suspensionStatus: 'סטטוס השעיה',
    table: 'טבלה',
    team: 'קבוצה',
    teams: 'קבוצות',
    teamsAndPlayers: 'קבוצות ושחקנים',
    team1: 'קבוצה 1',
    team2: 'קבוצה 2',
    thirdPlace: 'מקום שלישי',
    teamPage: 'עמוד קבוצה',
    teamPlayers: 'שחקני {{team}}',
    thisEmailIsNotAdmin: 'האימייל מחובר אך לא נמצא ב-admin_users.',
    time: 'שעה',
    today: 'היום',
    todayMatches: 'משחקי היום',
    topAdvance: '{{count}} הראשונות עולות',
    topQualify: '{{count}} הראשונות מעפילות',
    topTwoEachGroup: '2 הראשונות מכל בית מעפילות',
    topScorer: 'מלך השערים',
    tournamentStats: 'סטטיסטיקות הטורניר',
    tournamentWinner: 'זוכת הטורניר',
    tournamentTotals: 'סיכומי הטורניר',
    unavailable: 'לא זמין',
    unassisted: 'ללא בישול',
    adminLiveControl: 'ניהול משחק חי',
    closeBracket: 'סגור סוגר',
    closeEventForm: 'סגור טופס אירוע',
    closeQuickMode: 'סגור מצב מהיר',
    fieldSharing: 'שיתוף במגרש',
    lastMatches: 'משחקים אחרונים',
    noAssistPlayersFound: 'לא נמצאו שחקני בישול.',
    noPlayersAvailable: 'אין שחקנים זמינים',
    noRelatedMatchesYet: 'אין עדיין משחקים קשורים.',
    popUpBlockedPrint: 'החלון הקופץ נחסם. אפשר חלונות קופצים כדי להדפיס את הפוסטר.',
    preparing: 'מכין...',
    recentEventsUpdateImmediately: 'אירועים אחרונים מתעדכנים מיד לאחר השמירה.',
    searchAssistPlayer: 'חפש שחקן בישול',
    searchPlayer: 'חפש שחקן',
    searchPlayers: 'חפש שחקנים',
    share: 'שתף',
    shareImage: 'שתף תמונה',
    shareSheetOpened: 'חלון השיתוף נפתח.',
    sharing: 'שיתוף',
    sharingNotSupportedDownloaded: 'השיתוף לא נתמך בדפדפן הזה. התמונה הורדה במקום.',
    tournament: 'טורניר',
    tournamentTitle: 'גביע העולם דיר חנא',
    undoLastEvent: 'בטל אירוע אחרון',
    editLastEvent: 'ערוך אירוע אחרון',
    editEvent: 'ערוך אירוע',
    deleteEvent: 'מחק אירוע',
    deleteEventConfirm: 'למחוק את האירוע ולחשב מחדש את התוצאה/הסטטיסטיקה?',
    eventDeletedSuccessfully: 'האירוע נמחק בהצלחה.',
    correctLiveMinute: 'תקן דקת משחק',
    applyMinuteCorrection: 'החל דקה',
    minuteCorrectionHelp: 'השתמש בזה אם הפתיחה או המחצית השנייה התחילו באיחור. שעון המשחק ימשיך מהדקה המתוקנת.',
    confirmEvent: 'אשר {{event}}',
    endMatchConfirm: 'לסיים את המשחק ולשמור את התוצאה הנוכחית כסופית?',
    goalsAndAssists: 'שערים ובישולים',
    goalsAssistsByMatch: 'שערים / בישולים לפי משחק',
    goalsByMatch: 'שערים לפי משחק',
    goalsScored: 'שערים לזכות',
    goalsConceded: 'שערים נגד',
    mostScored: 'הכי הרבה שערים',
    fewestConceded: 'הכי מעט ספיגות',
    wins: 'ניצחונות',
    draws: 'תיקו',
    losses: 'הפסדים',
    wonShort: 'נ',
    drawnShort: 'ת',
    lostShort: 'ה',
    shortTable: 'טבלה קצרה',
    fullTable: 'טבלה מלאה',
    form: 'כושר',
    minutes: 'דקות',
    pendingStats: 'סטטיסטיקות בהמשך',
    pGdPts: 'מ / הפרש / נק׳',
    bracketViewer: 'צפייה בסוגר',
    bothTeams: 'שתי הקבוצות',
    matchShareCard: 'כרטיס שיתוף משחק',
    shareCardDestinations: 'אינסטגרם, וואטסאפ, פייסבוק, טלגרם',
    matchShareCardPreview: 'תצוגה מקדימה לכרטיס שיתוף',
    imageDownloaded: 'התמונה הורדה.',
    inviteAdmin: 'הזמן מנהל',
    inviteAdminDetail: 'הוסף אימייל מנהל מאושר נוסף',
    downloadImage: 'הורד תמונה',
    shareImageButton: 'שתף תמונה',
    generating: 'מייצר...',
    couldNotGenerateImage: 'לא ניתן לייצר תמונה.',
    posterDownloaded: 'הפוסטר הורד.',
    printDialogOpened: 'חלון ההדפסה נפתח.',
    couldNotGeneratePoster: 'לא ניתן לייצר פוסטר.',
    couldNotGenerateQrCode: 'לא ניתן לייצר קוד QR.',
    generatingQrPoster: 'מייצר פוסטר QR...',
    downloadPoster: 'הורד פוסטר',
    printPoster: 'הדפס פוסטר',
    qrPosterPreview: 'תצוגת פוסטר QR',
    openCameraAndScan: 'פתחו מצלמה וסרקו',
    noLoginRequiredForSpectators: 'אין צורך בהתחברות לצופים',
    matchCardShareText: 'כרטיס משחק של גביע העולם דיר חנא',
    theme: 'ערכת צבעים',
    edit: 'ערוך',
    relatedMatches: 'משחקים קשורים',
    square: 'ריבוע',
    story: 'סטורי',
    tbd: 'ייקבע',
    tournamentForm: 'כושר בטורניר',
    liveMatchesAria: 'הצג משחקים חיים',
    openLiveMatch: 'פתח משחק חי',
    favoriteMatch: 'משחק מועדף',
    favoriteTeamLabel: 'קבוצה מועדפת',
    minutesAutoCalculated: 'הדקות מחושבות אוטומטית במהלך משחק חי.',
    addEvent: 'הוסף אירוע',
    adminUpdates: 'עדכוני מנהל',
    adminUpdatesDetail: 'הזנת תוצאות ואירועים מאובטחת',
    cancelEvent: 'בטל אירוע',
    deleteMatchConfirm: 'למחוק את המשחק ואת האירועים שלו?',
    deletePlayer: 'מחק שחקן',
    deletePlayerConfirm: 'למחוק את {{name}}?',
    deleteTeam: 'מחק קבוצה',
    deleteTeamConfirm: 'למחוק את {{name}}? פעולה זו תמחק גם את השחקנים שלה.',
    editOrDelete: 'ערוך או מחק',
    finalResult: 'תוצאה סופית',
    fixture: 'משחק',
    fixtureSetup: 'הגדרת משחק',
    followLive: 'עקוב בלייב',
    goalscorers: 'כובשים',
    lineupsUnavailable: 'ההרכבים יופיעו לאחר אישור שתי הקבוצות.',
    managePlayers: 'ניהול שחקנים',
    manageTeams: 'ניהול קבוצות',
    mvpFirst: 'MVP קודם',
    noPlayersAdmin: 'אין עדיין שחקנים. הוסף סגלים אמיתיים לאחר יצירת קבוצות.',
    noTeamsYet: 'אין עדיין קבוצות. הוסף קודם את קבוצות הטורניר האמיתיות.',
    playerName: 'שם שחקן',
    playerNameArabic: 'שם שחקן - ערבית',
    playerNameEnglish: 'שם שחקן - אנגלית',
    playerNameHebrew: 'שם שחקן - עברית',
    primary: 'צבע ראשי',
    publicDashboard: 'לוח ציבורי',
    publicDashboardDetail: 'משחקים, תוצאות חיות, טבלאות ומובילים',
    pwaRelease: 'גרסת PWA',
    pwaReleaseDetail: 'גישה דרך קוד QR להתקנה',
    scoreAndDetails: 'תוצאה ופרטים',
    secondary: 'צבע משני',
    squadFull: 'הסגל מלא',
    squadManagement: 'ניהול סגל',
    squadSlots: 'מקומות בסגל',
    stage: 'שלב',
    startingSeven: 'שביעייה פותחת',
    teamName: 'שם קבוצה',
    teamNameArabic: 'שם קבוצה - ערבית',
    teamNameEnglish: 'שם קבוצה - אנגלית',
    teamNameHebrew: 'שם קבוצה - עברית',
    tournamentSetup: 'הגדרת טורניר',
    versionRoadmap: 'מפת דרכים לגרסה',
    tiebreakersSummary: 'שוברי שוויון: נקודות, ואז תוצאת ראש בראש.',
    semiFinalWinners: 'מנצחות חצי הגמר',
    winnersAdvance: 'המנצחות עולות',
    winnerAdvances: 'המנצח עולה',
    championDecided: 'האלופה נקבעת',
    thirdPlaceDecided: 'המקום השלישי נקבע',
    actionFailed: 'הפעולה נכשלה. נסה שוב.',
    adding: 'מוסיף...',
    saving: 'שומר...',
    deleting: 'מוחק...',
    teamAddedSuccessfully: 'הקבוצה נוספה בהצלחה.',
    playerAddedSuccessfully: 'השחקן נוסף בהצלחה.',
    matchAddedSuccessfully: 'המשחק נוסף בהצלחה.',
    changesSavedSuccessfully: 'השינויים נשמרו בהצלחה.',
    deletedSuccessfully: 'נמחק בהצלחה.',
    qualificationRequiresRematch: 'ההעפלה דורשת משחק חוזר.',
    rematchAdminSuggestion: 'יש לקבוע משחק חוזר ידנית דרך הוספת משחק. אל תקבע תאריך/שעה עד אישור המארגן.',
    venue: 'מגרש',
    vote: 'הצבע',
    votes: 'הצבעות',
    whoWillWin: 'מי ינצח?',
    yellowCard: 'כרטיס צהוב',
    yellowCards: 'כרטיסים צהובים',
  },
  ar: {
    addAssist: 'أضف تمريرة حاسمة',
    addGoal: 'أضف هدف',
    addMatch: 'أضف مباراة',
    addOwnGoal: 'أضف هدفا ذاتيا',
    addPlayer: 'أضف لاعب',
    addRedCard: 'أضف بطاقة حمراء',
    addTeam: 'أضف فريق',
    addYellowCard: 'أضف بطاقة صفراء',
    admin: 'الإدارة',
    adminAccess: 'دخول المدير',
    adminAccessConfirmed: 'تم تأكيد صلاحية المدير.',
    adminControlPanel: 'لوحة التحكم',
    adminEmail: 'بريد المدير',
    adminInviteError: 'تعذرت دعوة المدير.',
    adminInviteSuccess: 'يمكن لـ {{email}} تسجيل الدخول كمدير الآن.',
    adminSettings: 'إعدادات المدير',
    allTeams: 'كل الفرق',
    appearance: 'المظهر',
    assists: 'تمريرات حاسمة',
    assist: 'تمريرة حاسمة',
    back: 'رجوع',
    backToOverview: 'العودة إلى النظرة العامة',
    bestPlayer: 'أفضل لاعب',
    beFirstToVote: 'كن أول من يصوت',
    bench: 'دكة البدلاء',
    byDate: 'حسب التاريخ',
    byRound: 'حسب الجولة',
    byTeam: 'حسب الفريق',
    cancel: 'إلغاء',
    chartDataUnavailable: 'لا توجد بيانات للرسم بعد.',
    code: 'رمز',
    completed: 'مكتمل',
    competition: 'البطولة',
    compareTeams: 'مقارنة الفرق',
    connectingToSupabase: 'جاري الاتصال بـ Supabase.',
    contributions: 'المساهمات',
    currentData: 'البيانات الحالية',
    date: 'التاريخ',
    deleteMatch: 'حذف المباراة',
    developedBy: 'تطوير محمد رجب',
    details: 'التفاصيل',
    darkMode: 'الوضع الداكن',
    dismiss: 'إغلاق',
    draw: 'تعادل',
    drawAvailableForLeague: 'التعادل متاح في مباريات مرحلة المجموعات',
    disciplinaryEvent: 'حدث انضباطي',
    editMatch: 'تعديل المباراة',
    endFirstHalfHalftime: 'إنهاء الشوط الأول / الاستراحة',
    endMatch: 'إنهاء المباراة',
    eventTimeline: 'تسلسل الأحداث',
    eventType: 'نوع الحدث',
    eventSaveFailed: 'تعذر حفظ الحدث. حاول مرة أخرى.',
    expand: 'توسيع',
    favoriteTeam: 'الفريق المفضل',
    fixtures: 'مباريات',
    final: 'النهائي',
    finalScoreSaved: 'تم حفظ النتيجة النهائية. تم إغلاق إجراءات المباراة.',
    finishedMatchEditing: 'يمكنك تصحيح النتيجة وخط الأحداث بعد نهاية المباراة.',
    finished: 'انتهت',
    firstHalf: 'الشوط الأول',
    fullTime: 'نهاية المباراة',
    goal: 'هدف',
    goals: 'أهداف',
    goalDifferenceShort: 'فارق',
    group: 'المجموعة',
    groupA: 'المجموعة أ',
    groupB: 'المجموعة ب',
    groupStage: 'مرحلة المجموعات',
    halftime: 'استراحة',
    kickoff: 'بداية',
    knockout: 'الأدوار الإقصائية',
    knockoutMatch: 'مباراة إقصائية',
    knockoutPath: 'مسار الأدوار الإقصائية',
    language: 'اللغة',
    latestMatchday: 'آخر جولة',
    latestResults: 'آخر النتائج',
    league: 'مرحلة المجموعات',
    leagueStage: 'مرحلة المجموعات',
    leagueStandings: 'ترتيب المجموعات',
    leagueTable: 'جداول المجموعات',
    lineups: 'التشكيلات',
    lightMode: 'الوضع الفاتح',
    live: 'مباشر',
    liveMatch: 'مباراة مباشرة',
    liveMatchControl: 'تحكم المباراة المباشرة',
    liveMatches: 'مباريات مباشرة',
    liveNow: 'مباشر الآن',
    liveTableProvisional: 'ترتيب مباشر — مؤقت',
    loadingTournamentData: 'تحميل بيانات البطولة',
    localTournamentDashboard: 'لوحة البطولة المحلية',
    login: 'تسجيل الدخول',
    loginAsAdmin: 'دخول المدير',
    match: 'مباراة',
    matchCenter: 'مركز المباراة',
    matchEvents: 'أحداث المباراة',
    matchHistory: 'سجل المباريات',
    matchSetup: 'إعداد المباريات',
    matchday: 'الجولة',
    matches: 'المباريات',
    minute: 'الدقيقة',
    max: 'الحد الأقصى',
    mostAssists: 'الأكثر صناعة',
    nextMatch: 'المباراة القادمة',
    nextMatchday: 'الجولة القادمة',
    noAssist: 'بدون تمريرة',
    noGoalsOrAssistsYet: 'لا توجد أهداف أو تمريرات بعد.',
    noGoalsRecordedYet: 'لا توجد أهداف بعد.',
    noMatchEventsForMatchYet: 'لا توجد أحداث لهذه المباراة بعد.',
    noMatchEventsYet: 'لا توجد أحداث مباراة بعد.',
    noMatchHistoryYet: 'لا يوجد سجل مباريات بعد.',
    noMatchScheduledYet: 'لا توجد مباراة مجدولة بعد.',
    noMatchesAvailableForStageYet: 'لا توجد مباريات متاحة لهذه المرحلة.',
    noMatchesFoundForFilter: 'لا توجد مباريات لهذا الفلتر.',
    noMatchesScheduledYet: 'لا توجد مباريات مجدولة بعد.',
    noMatchesToday: 'لا توجد مباريات اليوم.',
    noPlayersFound: 'لم يتم العثور على لاعبين.',
    noPlayersYet: 'لا يوجد لاعبون بعد.',
    noPlayersRegistered: 'لا يوجد لاعبون مسجلون',
    noRecordYet: 'لا يوجد سجل بعد',
    overview: 'نظرة عامة',
    ownGoal: 'هدف ذاتي',
    ownGoalDetail: 'يتم احتساب الهدف للفريق المنافس.',
    ownGoalScorer: 'مسجل الهدف الذاتي',
    ownGoalTeamHelp: 'اختر فريق اللاعب. ستضاف النتيجة تلقائيا للفريق المنافس.',
    pageNotFound: 'الصفحة غير موجودة',
    pageNotFoundDetail: 'تعذر العثور على صفحة البطولة هذه. ربما تمت إزالتها أو أن الرابط قديم.',
    pause: 'إيقاف مؤقت',
    paused: 'متوقف مؤقتا',
    penalty: 'ركلة جزاء',
    penaltyGoal: 'هدف من ركلة جزاء',
    penaltyGoalDetail: 'تم تسجيل ركلة الجزاء.',
    penaltyMissSaved: 'ضائعة/تصدى لها',
    penaltyMissSavedDetail: 'تم إضاعة ركلة الجزاء أو التصدي لها.',
    penaltyResult: 'نتيجة ركلة الجزاء',
    penaltyShooter: 'منفذ ركلة الجزاء',
    passAccuracy: 'دقة التمرير',
    player: 'لاعب',
    playerAlreadySentOff: 'تم طرد اللاعب بالفعل.',
    playerProfile: 'ملف اللاعب',
    players: 'لاعبون',
    playersCount: 'لاعبون',
    playedShort: 'لعب',
    points: 'النقاط',
    pointsShort: 'نقاط',
    previousMatches: 'مباريات سابقة',
    qualificationRace: 'سباق التأهل',
    qualificationRules: 'قوانين التأهل',
    quickLinks: 'روابط سريعة',
    quickMode: 'الوضع السريع',
    qrPoster: 'QR / ملصق',
    rank: 'الترتيب',
    ranking: 'المركز',
    recentFixtures: 'مباريات حديثة',
    recentForm: 'الشكل الأخير',
    redCard: 'بطاقة حمراء',
    redCards: 'بطاقات حمراء',
    readyForRealData: 'جاهز لبيانات البطولة الحقيقية',
    record: 'السجل',
    realDataEmptyState: 'لم تعد فرق ولاعبو ومباريات وإحصائيات التجربة مستخدمة. سجّل كمدير لإضافة الفرق والتشكيلات والمباريات وأحداثها الحقيقية يدويا.',
    resume: 'استئناف',
    round: 'جولة',
    roundShort: 'الجولة {{round}}',
    rules: 'القوانين',
    save: 'حفظ',
    saveDetails: 'حفظ التفاصيل',
    schedule: 'الجدول',
    scheduled: 'مجدولة',
    scanToFollow: 'امسح لمتابعة المباريات المباشرة، الترتيب، الهدافين والنتائج',
    scorer: 'المسجل',
    score: 'النتيجة',
    secondHalf: 'الشوط الثاني',
    secondYellowDismissal: 'طرد تلقائي بعد البطاقة الصفراء الثانية.',
    secondYellowRedCard: 'صفراء ثانية → بطاقة حمراء',
    selectRound: 'اختر الجولة',
    selectTeam: 'اختر الفريق',
    selectPlayer: 'اختر اللاعب',
    semiFinal: 'نصف النهائي',
    semiFinals: 'نصف النهائي',
    sendLoginLink: 'إرسال رابط الدخول',
    scheduleRematch: 'جدولة مباراة إعادة',
    shareTeam: 'مشاركة الفريق',
    shots: 'تسديدات',
    singleGameBracket: 'نظام خروج بمباراة واحدة',
    signOut: 'تسجيل الخروج',
    signedInAs: 'مسجل كـ',
    startsIn: 'تبدأ بعد',
    startMatch: 'ابدأ المباراة',
    startSecondHalf: 'ابدأ الشوط الثاني',
    standings: 'الترتيب',
    standingsAvailableForLeague: 'الترتيب متاح لمباريات مرحلة المجموعات.',
    standingsPreview: 'معاينة الترتيب',
    standaloneAssistEvent: 'حدث تمريرة حاسمة منفصل',
    starters: 'أساسيون',
    stats: 'الإحصائيات',
    status: 'الحالة',
    statistics: 'إحصائيات',
    suspended: 'موقوف',
    suspendedPlayers: 'لاعبون موقوفون',
    suspensionStatus: 'حالة الإيقاف',
    table: 'الجدول',
    team: 'الفريق',
    teams: 'الفرق',
    teamsAndPlayers: 'الفرق واللاعبون',
    team1: 'الفريق 1',
    team2: 'الفريق 2',
    thirdPlace: 'المركز الثالث',
    teamPage: 'صفحة الفريق',
    teamPlayers: 'لاعبو {{team}}',
    thisEmailIsNotAdmin: 'هذا البريد مسجل لكنه غير موجود في admin_users.',
    time: 'الوقت',
    today: 'اليوم',
    todayMatches: 'مباريات اليوم',
    topAdvance: 'أفضل {{count}} يتأهلون',
    topQualify: 'أفضل {{count}} يتأهلون',
    topTwoEachGroup: 'أفضل فريقين من كل مجموعة يتأهلان',
    topScorer: 'الهداف',
    tournamentStats: 'إحصائيات البطولة',
    tournamentWinner: 'الفائز بالبطولة',
    tournamentTotals: 'إجمالي البطولة',
    unavailable: 'غير متاح',
    unassisted: 'بدون تمريرة حاسمة',
    adminLiveControl: 'تحكم مباشر للمدير',
    closeBracket: 'إغلاق المسار',
    closeEventForm: 'إغلاق نموذج الحدث',
    closeQuickMode: 'إغلاق الوضع السريع',
    fieldSharing: 'مشاركة في الملعب',
    lastMatches: 'آخر المباريات',
    noAssistPlayersFound: 'لم يتم العثور على لاعبي تمريرة حاسمة.',
    noPlayersAvailable: 'لا يوجد لاعبون متاحون',
    noRelatedMatchesYet: 'لا توجد مباريات مرتبطة بعد.',
    popUpBlockedPrint: 'تم حظر النافذة المنبثقة. اسمح بالنوافذ المنبثقة لطباعة الملصق.',
    preparing: 'جاري التحضير...',
    recentEventsUpdateImmediately: 'تتحدث الأحداث الأخيرة فورا بعد الحفظ.',
    searchAssistPlayer: 'ابحث عن لاعب للتمريرة',
    searchPlayer: 'ابحث عن لاعب',
    searchPlayers: 'ابحث عن لاعبين',
    share: 'مشاركة',
    shareImage: 'مشاركة الصورة',
    shareSheetOpened: 'تم فتح نافذة المشاركة.',
    sharing: 'المشاركة',
    sharingNotSupportedDownloaded: 'المشاركة غير مدعومة في هذا المتصفح. تم تنزيل الصورة بدلا من ذلك.',
    tournament: 'البطولة',
    tournamentTitle: 'موندياليتو ديرحنا',
    undoLastEvent: 'تراجع عن آخر حدث',
    editLastEvent: 'تعديل آخر حدث',
    editEvent: 'تعديل الحدث',
    deleteEvent: 'حذف الحدث',
    deleteEventConfirm: 'حذف هذا الحدث وإعادة حساب النتيجة والإحصائيات؟',
    eventDeletedSuccessfully: 'تم حذف الحدث بنجاح.',
    correctLiveMinute: 'تصحيح دقيقة المباراة',
    applyMinuteCorrection: 'تطبيق الدقيقة',
    minuteCorrectionHelp: 'استخدم هذا إذا بدأت المباراة أو الشوط الثاني متأخرا. سيكمل المؤقت من الدقيقة المصححة.',
    confirmEvent: 'تأكيد {{event}}',
    endMatchConfirm: 'إنهاء المباراة وحفظ النتيجة الحالية كنتيجة نهائية؟',
    goalsAndAssists: 'الأهداف والتمريرات',
    goalsAssistsByMatch: 'الأهداف / التمريرات حسب المباراة',
    goalsByMatch: 'الأهداف حسب المباراة',
    goalsScored: 'أهداف مسجلة',
    goalsConceded: 'أهداف مستقبلة',
    mostScored: 'الأكثر تسجيلا',
    fewestConceded: 'الأقل استقبالا',
    wins: 'انتصارات',
    draws: 'تعادلات',
    losses: 'خسائر',
    wonShort: 'ف',
    drawnShort: 'ت',
    lostShort: 'خ',
    shortTable: 'جدول مختصر',
    fullTable: 'جدول كامل',
    form: 'الشكل',
    minutes: 'دقائق',
    pendingStats: 'إحصائيات لاحقا',
    pGdPts: 'لعب / فارق / نقاط',
    bracketViewer: 'عارض المسار',
    bothTeams: 'الفريقان',
    matchShareCard: 'بطاقة مشاركة المباراة',
    shareCardDestinations: 'إنستغرام، واتساب، فيسبوك، تلغرام',
    matchShareCardPreview: 'معاينة بطاقة المشاركة',
    imageDownloaded: 'تم تنزيل الصورة.',
    inviteAdmin: 'دعوة مدير',
    inviteAdminDetail: 'أضف بريد مدير معتمد آخر',
    downloadImage: 'تنزيل الصورة',
    shareImageButton: 'مشاركة الصورة',
    generating: 'جاري الإنشاء...',
    couldNotGenerateImage: 'تعذر إنشاء الصورة.',
    posterDownloaded: 'تم تنزيل الملصق.',
    printDialogOpened: 'تم فتح نافذة الطباعة.',
    couldNotGeneratePoster: 'تعذر إنشاء الملصق.',
    couldNotGenerateQrCode: 'تعذر إنشاء رمز QR.',
    generatingQrPoster: 'جاري إنشاء ملصق QR...',
    downloadPoster: 'تنزيل الملصق',
    printPoster: 'طباعة الملصق',
    qrPosterPreview: 'معاينة ملصق QR',
    openCameraAndScan: 'افتح الكاميرا وامسح',
    noLoginRequiredForSpectators: 'لا يحتاج الجمهور إلى تسجيل الدخول',
    matchCardShareText: 'بطاقة مباراة كأس العالم دير حنا',
    theme: 'السمة',
    edit: 'تعديل',
    relatedMatches: 'مباريات مرتبطة',
    square: 'مربع',
    story: 'ستوري',
    tbd: 'يحدد لاحقا',
    tournamentForm: 'شكل البطولة',
    liveMatchesAria: 'عرض المباريات المباشرة',
    openLiveMatch: 'فتح المباراة المباشرة',
    favoriteMatch: 'المباراة المفضلة',
    favoriteTeamLabel: 'الفريق المفضل',
    minutesAutoCalculated: 'يتم حساب الدقائق تلقائيا أثناء المباريات المباشرة.',
    addEvent: 'أضف حدث',
    adminUpdates: 'تحديثات المدير',
    adminUpdatesDetail: 'إدخال آمن للنتائج والأحداث',
    cancelEvent: 'إلغاء الحدث',
    deleteMatchConfirm: 'حذف هذه المباراة وأحداثها؟',
    deletePlayer: 'حذف اللاعب',
    deletePlayerConfirm: 'حذف {{name}}؟',
    deleteTeam: 'حذف الفريق',
    deleteTeamConfirm: 'حذف {{name}}؟ سيتم حذف لاعبيه أيضا.',
    editOrDelete: 'تعديل أو حذف',
    finalResult: 'النتيجة النهائية',
    fixture: 'موعد المباراة',
    fixtureSetup: 'إعداد المباراة',
    followLive: 'تابع مباشرة',
    goalscorers: 'المسجلون',
    lineupsUnavailable: 'ستظهر التشكيلات بعد تأكيد الفريقين.',
    managePlayers: 'إدارة اللاعبين',
    manageTeams: 'إدارة الفرق',
    mvpFirst: 'النسخة الأولى أولا',
    noPlayersAdmin: 'لا يوجد لاعبون بعد. أضف التشكيلات الحقيقية بعد إنشاء الفرق.',
    noTeamsYet: 'لا توجد فرق بعد. أضف فرق البطولة الحقيقية أولا.',
    playerName: 'اسم اللاعب',
    playerNameArabic: 'اسم اللاعب - العربية',
    playerNameEnglish: 'اسم اللاعب - الإنجليزية',
    playerNameHebrew: 'اسم اللاعب - العبرية',
    primary: 'اللون الأساسي',
    publicDashboard: 'لوحة الجمهور',
    publicDashboardDetail: 'المباريات، النتائج المباشرة، الجداول والمتصدرون',
    pwaRelease: 'إصدار PWA',
    pwaReleaseDetail: 'وصول قابل للتثبيت عبر QR',
    scoreAndDetails: 'النتيجة والتفاصيل',
    secondary: 'اللون الثانوي',
    squadFull: 'القائمة ممتلئة',
    squadManagement: 'إدارة القائمة',
    squadSlots: 'أماكن القائمة',
    stage: 'المرحلة',
    startingSeven: 'السبعة الأساسيون',
    teamName: 'اسم الفريق',
    teamNameArabic: 'اسم الفريق - العربية',
    teamNameEnglish: 'اسم الفريق - الإنجليزية',
    teamNameHebrew: 'اسم الفريق - العبرية',
    tournamentSetup: 'إعداد البطولة',
    versionRoadmap: 'خارطة طريق النسخة',
    tiebreakersSummary: 'كسر التعادل: النقاط ثم نتيجة المواجهة المباشرة.',
    semiFinalWinners: 'فائزو نصف النهائي',
    winnersAdvance: 'الفائزون يتأهلون',
    winnerAdvances: 'الفائز يتأهل',
    championDecided: 'تحديد البطل',
    thirdPlaceDecided: 'تحديد المركز الثالث',
    actionFailed: 'فشلت العملية. حاول مرة أخرى.',
    adding: 'جاري الإضافة...',
    saving: 'جاري الحفظ...',
    deleting: 'جاري الحذف...',
    teamAddedSuccessfully: 'تمت إضافة الفريق بنجاح.',
    playerAddedSuccessfully: 'تمت إضافة اللاعب بنجاح.',
    matchAddedSuccessfully: 'تمت إضافة المباراة بنجاح.',
    changesSavedSuccessfully: 'تم حفظ التغييرات بنجاح.',
    deletedSuccessfully: 'تم الحذف بنجاح.',
    qualificationRequiresRematch: 'التأهل يحتاج إلى مباراة إعادة.',
    rematchAdminSuggestion: 'يجب جدولة مباراة الإعادة يدويا من إضافة مباراة. لا تحدد التاريخ/الوقت حتى يؤكد المنظم.',
    venue: 'الملعب',
    vote: 'صوّت',
    votes: 'أصوات',
    whoWillWin: 'من سيفوز؟',
    yellowCard: 'بطاقة صفراء',
    yellowCards: 'بطاقات صفراء',
  },
}

function clean(value) {
  return typeof value === 'string' ? value.trim() : ''
}

function firstValue(...values) {
  return values.map(clean).find(Boolean) ?? ''
}

function interpolate(template, values = {}) {
  return Object.entries(values).reduce(
    (text, [key, value]) => text.replaceAll(`{{${key}}}`, String(value)),
    template,
  )
}

function missingTranslation(language, key) {
  if (
    typeof import.meta !== 'undefined' &&
    import.meta.env?.DEV &&
    typeof console !== 'undefined'
  ) {
    console.warn(`[i18n] Missing translation key "${key}" for "${language}".`)
  }
}

export function normalizeLanguage(language) {
  return languageOptions.some((option) => option.id === language) ? language : fallbackLanguage
}

export function getStoredLanguage() {
  if (typeof window === 'undefined') {
    return defaultLanguage
  }

  const storedLanguage = window.localStorage.getItem(languageStorageKey)
  return storedLanguage ? normalizeLanguage(storedLanguage) : defaultLanguage
}

export function storeLanguage(language) {
  if (typeof window !== 'undefined') {
    window.localStorage.setItem(languageStorageKey, normalizeLanguage(language))
  }
}

export function getLanguageDirection(language) {
  return languageOptions.find((option) => option.id === normalizeLanguage(language))?.direction ?? 'ltr'
}

export function getUiDictionary(language = fallbackLanguage) {
  const normalizedLanguage = normalizeLanguage(language)
  const fallbackDictionary = uiTranslations[fallbackLanguage]
  const activeDictionary = uiTranslations[normalizedLanguage] ?? {}
  const dictionary = {
    ...fallbackDictionary,
    ...activeDictionary,
  }

  function t(key, values) {
    if (!(key in activeDictionary) && normalizedLanguage !== fallbackLanguage) {
      missingTranslation(normalizedLanguage, key)
    }

    if (!(key in fallbackDictionary)) {
      missingTranslation(fallbackLanguage, key)
    }

    return interpolate(dictionary[key] ?? key, values)
  }

  return new Proxy(
    {
      ...dictionary,
      currentLanguage: normalizedLanguage,
      t,
    },
    {
      get(target, property) {
        if (typeof property !== 'string' || property in target) {
          return target[property]
        }

        missingTranslation(normalizedLanguage, property)
        return fallbackDictionary[property] ?? property
      },
    },
  )
}

export function getTeamName(team, language = fallbackLanguage) {
  if (!team) return 'TBD'

  if (language === 'he') return firstValue(team.countryHe, team.countryEn, team.country)
  if (language === 'ar') return firstValue(team.countryAr, team.countryEn, team.country)
  return firstValue(team.countryEn, team.country)
}

export function getPlayerName(player, language = fallbackLanguage) {
  if (!player) return ''

  if (language === 'he') return firstValue(player.nameHe, player.nameEn, player.name)
  if (language === 'ar') return firstValue(player.nameAr, player.nameEn, player.name)
  return firstValue(player.nameEn, player.name)
}

export function getVenueName(match, language = fallbackLanguage) {
  const normalizedLanguage = normalizeLanguage(language)

  if (normalizedLanguage === 'he') {
    return firstValue(tournamentFormat.fixedVenueHe, match?.venueHe, match?.venueEn, match?.venue)
  }

  if (normalizedLanguage === 'ar') {
    return firstValue(tournamentFormat.fixedVenueAr, match?.venueAr, match?.venueEn, match?.venue)
  }

  return firstValue(tournamentFormat.fixedVenueEn, match?.venueEn, match?.venue)
}

export function getPlayerNameCandidates(player) {
  return Array.from(new Set([
    clean(player?.name),
    clean(player?.nameEn),
    clean(player?.nameHe),
    clean(player?.nameAr),
  ].filter(Boolean)))
}

export function getEventPlayerName(event, players = [], language = fallbackLanguage) {
  const normalizedLanguage = normalizeLanguage(language)
  const eventPlayerId = clean(event?.playerId)
  const storedEventName = clean(event?.player)
  const normalizedStoredName = storedEventName.toLocaleLowerCase()
  const player = eventPlayerId
    ? players.find((item) => clean(item?.id) === eventPlayerId)
    : players.find((item) =>
        getPlayerNameCandidates(item).some(
          (candidate) => candidate.toLocaleLowerCase() === normalizedStoredName,
        ),
      )

  return player ? getPlayerName(player, normalizedLanguage) : storedEventName
}

export function localizeTournamentData(data, language) {
  const normalizedLanguage = normalizeLanguage(language)
  const localizeMatch = (match) => ({
    ...match,
    events: (match.events ?? []).map((event) => ({
      ...event,
      playerDisplayName: getEventPlayerName(event, data.players, normalizedLanguage),
    })),
    venue: getVenueName(match, normalizedLanguage),
  })

  return {
    ...data,
    teams: data.teams.map((team) => ({
      ...team,
      country: getTeamName(team, normalizedLanguage),
    })),
    players: data.players.map((player) => ({
      ...player,
      name: getPlayerName(player, normalizedLanguage),
    })),
    matches: data.matches.map(localizeMatch),
    knockoutMatches: data.knockoutMatches.map(localizeMatch),
  }
}
